### PR TITLE
Initial Upload (serviceScout)

### PR DESCRIPTION
**Pull request by blankAccount01**
# BrowserBuddy Extension Submission

## Project Details

1. **What is the name of your project?**
   It's called service scout

3. **How many hours did you spend developing this?**  
    Around 3-4 hours

4. **What problem does your extension solve, or what makes it unique?**  
    I've recently started making websites and I need a simple tool to check that users can access it at all times. This just makes it easy to check when I open my browser

5. **How many people have tested your extension?**  
    4 people (my friends)

6. **Does your extension work in both Chrome and Firefox?**  
    Yes, it does (V3)

---

## Additional Comments

None

### CODE REVIEW

**Comment by JosiasAurel** [comment]
I just tried the extension and it doesn't seem to be working... anything I may be doing wrong? 
The screenshot below is me having entered the link to my personal site and it says it's unreachable meanwhile it's currently opened in my browwser. 

image

**Comment by JosiasAurel** [comment]
Also please fix this error
image

**Comment by blankAccount01** [comment]
Hi, I've fixed the problem which was some faulty regex code that appended .com onto URLs that had a / and subsequent queries at the end. I've also removed the background scripts in the manifest which should fix the extension error. 

Regarding this, Firefox currently only supports background scripts while Chrome requires the use of service workers so how do we do this in both Chrome and Firefox? 

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background#browser_support
Mozilla's article on this topic suggests putting both in the manifest ?!?

Thanks : )

**Review by JosiasAurel — APPROVED** [review]
Don't worry about firefox support for now. I'm aware manifest version 3 isn't fully supported there.

To get your grant, please fill [this form](https://airtable.com/appgtKZwZBoOeFU7O/pagyeS51zr2kC1rp0/form).

**Pull request merged**
