### PR TITLE
submitting bitcoin calculator

### PR DESCRIPTION
**Pull request by eesazahed**
### Project Details
1. **What is the name of your project?** Bitcoin calculator

3. **How many hours did you spend developing this?**  3

4. **What problem does your extension solve, or what makes it unique?**  It solves the problem of knowing how much Bitcoin you have in USD. Some people have small amounts, like 0.004341 Bitcoin and it's inconvenient to Google it every time. This also uses local storage to remember how much bitcoin the user has. Some users use hardware wallets, which don't have instant calculation features like web wallets. For those users, this chrome extension will be very useful.

5. **How many people have tested your extension?**  5

6. **Does your extension work in both Chrome and Firefox?**  It does.
---

### Additional Comments

have a nice day

### CODE REVIEW

**Review by JosiasAurel — CHANGES_REQUESTED** [review]
To be frank, I don't see anything peculiar about this extension. One could easily just Google the conversion themselves (where they will have even more currency conversion options). 

How about you try brainstorming an idea here 
 - https://browserbuddy.hackclub.com/inspiration

**Comment by eesazahed** [comment]
Say you own 0.09124837 bitcoin. Instead of Googling it, you can just click a button on the top right of your screen that shows how much it is worth currently.

It's all to make it more convenient. A chrome extension that saves your exact amount of Bitcoin in local storage calculates everything in one click. It saves time in comparison to getting the bitcoin price and multiplying it to the amount of BTC they own.

**Comment by eesazahed** [comment]
I'd rather save the user a few seconds, which is kinda the point of chrome extensions (see the gif)

gif

**Comment by JosiasAurel** [comment]
I don't think this extension has a compelling value proposition.

**Pull request closed without merging**
