### PR TITLE
Auto-tyer

### PR DESCRIPTION
**Pull request by YashasSingh**
# BrowserBuddy Extension Submission

## Project Details

1. **What is the name of your project?**
Auto-typer
2. **How many hours did you spend developing this?**  
   _(Give your best estimate)_
6-7
3. **What problem does your extension solve, or what makes it unique?**  
   _(Provide a brief description of the functionality or innovation)_
Its basically copy and pasting but it gives a human feel to it by having it be a changing speed, screwups and fixing that mistake and easy control binds
4. **How many people have tested your extension?**  
   _(We recommend at least 3)_
3  unfortunately
5. **Does your extension work in both Chrome and Firefox?**  
   _(Your extension must be compatible with both browsers)_
yes
---

## Additional Comments

(Feel free to provide any additional context or notes here)

### CODE REVIEW

**Review by JosiasAurel — CHANGES_REQUESTED** [review]
This appears to be a different extension that what you describe in the PR.

**Comment by YashasSingh** [comment]
Oh no, i submitted the wrong file, that was my friends project he asked me to try, I think I fixed it now. I'm sorry about that

**Review by JosiasAurel — CHANGES_REQUESTED** [review]
Can you give me a situation or any reason when one would want to use this extension?

**Comment by YashasSingh** [comment]
My original idea was for situations like meetings or tutorials, where you want to demonstrate code effectively. This extension lets you avoid manually typing everything out, saving time and allowing you to narrate your thought process as it types, creating a smoother and more engaging experience for your audience.

**Comment by JosiasAurel** [comment]
That doesn't sound like a good use-case. One could just have multiple screenshots of the code with just what he needs to explain. 

Also closing as we're past deadline.

**Pull request closed without merging**
