### PR TITLE
High Seas Doubloons Extension

### PR DESCRIPTION
**Pull request by MohammedMMC**
### Project Details
1. **What is the name of your project?**
High Seas Doubloons Extension

2. **How many hours did you spend developing this?**  
   _(Give your best estimate)_
  5 hours

3. **What problem does your extension solve, or what makes it unique?**  
   _(Provide a brief description of the functionality or innovation)_
Each time I shipped a project I find myself wondering how many votes I got and how many Doubloons I earned per hour I used to waste a lot of time calculating these numbers manually thats why I made this extension to save time and satisfy my curiosity :) If you want to know more, reading the README file would be awesome! Thanks <3

4. **How many people have tested your extension?**  
   _(We recommend at least 3)_
3 including me

5. **Does your extension work in both Chrome and Firefox?**  
   _(Your extension must be compatible with both browsers)_
Yes

---

### Additional Comments
(Feel free to provide any additional context or notes here)

### CODE REVIEW

**Comment by JosiasAurel** [comment]
please can you include a demo video/screenshot of this extension working?

**Comment by JosiasAurel** [comment]
image

i also get this error when i open my high-seas dashboard

**Comment by MohammedMMC** [comment]
> **Can you include a demo video/screenshot of this extension working?**  

I’ve uploaded this image ("view.jpg"): View Screenshot.  

---

> **I also get this error when I open my High Seas dashboard.**  

This error might happen if you don’t have any ships or if you are still in the tutorial.  
I believe I fixed it but if you already have ships and the error happens please send me a screenshot of your Shipyard page so I can investigate further and try to resolve it.

---

Thanks.

**Comment by MohammedMMC** [comment]
I think you might have a pending ship that is still waiting to receive votes and that's why you are getting the error :')
I forgot to think about this condition, but now it should now be fixed.

**Comment by MohammedMMC** [comment]
I added a new feature that shows you how many Doubloons you might earn while your ship is still pending.  :)
Expected View.

**Review by JosiasAurel — APPROVED** [review]
Cool. If you haven't yet, please fill [this form](https://airtable.com/appgtKZwZBoOeFU7O/pagyeS51zr2kC1rp0/form) to get your grant.

**Pull request merged**
