### PR TITLE
github-search extension

### PR DESCRIPTION
**Pull request by not-first**
### Project Details
1. **What is the name of your project?**
Github search.

3. **How many hours did you spend developing this?**  
Hackatime measured 6 hours 23 minutes.

4. **What problem does your extension solve, or what makes it unique?**  
   It provides an easier way to access repositories which can be hard to access through the github ui, and allows a central place to open personal repositories, starred ones and ones in your browser history.

5. **How many people have tested your extension?**  
2
6. **Does your extension work in both Chrome and Firefox?**  
It uses manifest v3, so it works in chrome but not in firefox.
---

### CODE REVIEW

**Comment by JosiasAurel** [comment]
Ping here! Deadline is Nov 30 👀

**Comment by not-first** [comment]
Oh sorry! All of my repos seem to be showing up. I believe it could be  limited by the github repository api which only allows the retrieval of 100 repositories at a time. I will have to see if I can implement some sort of refetching until all repositories are received, although it might be hard as I do not have enough to test.

**Comment by not-first** [comment]
@JosiasAurel I have attempted to fix the issue. Although I am unable to test it, support for over 100 repositories should have been added. Hopefully the issue is fixed, just in time for the deadline!

**Review by JosiasAurel — APPROVED** [review]
Awesome it works now! If you haven't yet, please fill [this form](https://airtable.com/appgtKZwZBoOeFU7O/pagyeS51zr2kC1rp0/form) to get your grant.

**Pull request merged**
