### PR TITLE
add files: StudyMate v0.1.3

### PR DESCRIPTION
**Pull request by ThatFrogDev**
# BrowserBuddy Extension Submission

## Project Details

1. **What is the name of your project?**
StudyMate

2. **How many hours did you spend developing this?**  
   _(Give your best estimate)_
Approximately nine hours

3. **What problem does your extension solve, or what makes it unique?**  
   _(Provide a brief description of the functionality or innovation)_
StudyMate is an extension for people with ADHD, that can't focus on a task and get distracted too easily. It is based on the pomodoro timer principe. On top of that, it has a nice aesthetic.

4. **How many people have tested your extension?**  
   _(We recommend at least 3)_
I have tested it, but on a lot of different browsers and testing was really part of my process. I've tested it on Arc, Google Chrome and Firefox both by loading the extension in from a folder (the built extension) and in debug mode.

On top of that, my friend also tested it on Zen Browser and it worked great there as well.

5. **Does your extension work in both Chrome and Firefox?**  
   _(Your extension must be compatible with both browsers)_
Yes, my extension works on both Chrome and Firefox. If you want to build it, you should run `pnpm build` for Chrome and `pnpm build:firefox` for Firefox.

---

### CODE REVIEW

**Review by JosiasAurel — CHANGES_REQUESTED** [review]
How is it different from other pomodoro timer extensions out there?

**Comment by ThatFrogDev** [comment]
> How is it different from other pomodoro timer extensions out there?

Hi Josias,

The main difference **right now** are the aesthetics. I generally wouldn't use any other Pomodoro timer just because they look really bland. You can find screenshots and video examples on the README.

However, there are a ton of features planned. A few of them are also in the README, but if you'd like me to elaborate, please let me know.

**Comment by JosiasAurel** [comment]
Please try to add something that adds something functionaly unique

**Comment by ThatFrogDev** [comment]
@JosiasAurel I don't really have time to do that before the end of today, but I actually know something lots of pomodoro extensions don't have - the ability to see how many times you used a timer. For example, if my pomodoro timer finishes two times, it would say "Pomodoro (2)". Is this enough to get accepted or would I need to add a bit more? Hope it is

**Review by JosiasAurel — CHANGES_REQUESTED** [review]
No unfortunately that's not enough. I don't see that as a compelling

**Pull request closed without merging**
