### PR TITLE
Added my christmas extension: Festive Frenzy

### PR DESCRIPTION
**Pull request by amoghagrawal**
# BrowserBuddy Extension Submission

## Project Details

1. **What is the name of your project?**
   _Festive Frenzy_

2. **How many hours did you spend developing this?**  
   _5.8_

3. **What problem does your extension solve, or what makes it unique?**  
   _It is a Christmas - themed extension that checks if the tab is active and adds snowfall, random emojis and plays a Christmas theme song if enabled_

4. **How many people have tested your extension?**  
   _4_

5. **Does your extension work in both Chrome and Firefox?**  
   _Yes_

---

## Additional Comments
Added my new extension for v2 and also updated the old one with some UI changes

### CODE REVIEW

**Review by JosiasAurel — CHANGES_REQUESTED** [review]
I like the idea. Have you tried keeping the extension running for some time? It might be leaking some memory. 
image

**Comment by amoghagrawal** [comment]
Oh god! How did I miss this, I will try to fix this and merge the new code here

**Comment by amoghagrawal** [comment]
I have fixed the memory loss now and the extension should work better now

**Review by JosiasAurel — APPROVED** [review]
Awesome! If you haven't yet, please fill [this form](https://airtable.com/appgtKZwZBoOeFU7O/pagyeS51zr2kC1rp0/form) to get your grant.

**Comment by amoghagrawal** [comment]
Thankyou! I had filled the grant form earlier only when I made the pull request

**Pull request closed without merging**
