### PR TITLE
FormGini

### PR DESCRIPTION
**Pull request by ktshacx**
### Project Details
1. **What is the name of your project?**
FormGini
2. **How many hours did you spend developing this?**  
   _(Give your best estimate)_
5-6 hours
3. **What problem does your extension solve, or what makes it unique?**  
   _(Provide a brief description of the functionality or innovation)_
It automatically add a button at google forms to answer questions via open ai
4. **How many people have tested your extension?**  
   _(We recommend at least 3)_
me and my friends 1-3
5. **Does your extension work in both Chrome and Firefox?**  
   _(Your extension must be compatible with both browsers)_
yup
---

### Additional Comments
(Feel free to provide any additional context or notes here)

### CODE REVIEW

**Comment by ktshacx** [comment]
ping !!

**Comment by ktshacx** [comment]
please give reviews on it

**Comment by JosiasAurel** [comment]
looking at it now

**Review by JosiasAurel — CHANGES_REQUESTED** [review]
This looks interesting. However I have two concerns
1. How does it know what information to fill into a Google Form? What's the use case?
2. I've set my OpenAI API key but the extension seems to be failing. Here's a screenshot from the extensions dashboard in Chrome
image

**Comment by JosiasAurel** [comment]
Closing as we're past deadline

**Pull request closed without merging**
