### PR TITLE
Add submission

### PR DESCRIPTION
**Pull request by giragon6**
### Project Details
1. **What is the name of your project?**

Hearth

2. **How many hours did you spend developing this?**  

8 (somehow)

3. **What problem does your extension solve, or what makes it unique?**  

Hearth lets you track your streak for a goal/habit you want to build (ex. drinking 64oz of water) and has a dragon that grows with your streak

Unlike other streak apps, it lets you track any streak instead of a specific category, and it features a dragon (which makes it far more motivating for me, anyway)

4. **How many people have tested your extension?**  
4

5. **Does your extension work in both Chrome and Firefox?**  
Yes
---

### Additional Comments
I used React and Tailwind so the file is pretty hefty, hence the .zip

### CODE REVIEW

**Comment by JosiasAurel** [comment]
There's nothing to review here. Was this a mistake?
image

**Comment by giragon6** [comment]
That's weird that it says that -- I added a .ZIP file since it was pretty big, so maybe that's why? This is what it shows on my screen: 
image

Here's the [file](https://drive.google.com/file/d/1NNw-demN6AsplSvqwgyQXloWLSEa8zj9/view?usp=sharing) too

**Comment by JosiasAurel** [comment]
It should not be a zip file. You have to directly include the source code in a folder carrying the name of your project under **submission** folder.

**Review by JosiasAurel — CHANGES_REQUESTED** [review]
You're missing a manifest in your extension
image

**Comment by giragon6** [comment]
Oh, I built mine with React so you open the dist file when you load it --
there's a manifest file in there. Let me know if that doesn't work!

**Pull request merged**
