### PR TITLE
Snowy - By Pizzalover125

### PR DESCRIPTION
**Pull request by pizzalover125**
# Snowy

Spent around 1-2 hours. 

Doesn't really solve a problem --> Simply adds a bit of snowy flair to each webpage. 

Three people have tested it. 

Compatible with Firefox and Chrome.

### CODE REVIEW

**Review by JosiasAurel — CHANGES_REQUESTED** [review]
There's an existing submission that does the same thing. Can you try coming up with something different?

**Comment by pizzalover125** [comment]
I tried being different by having some "glowing" snow and having the snow be partly opaque so it doesn't get in the way. I understand your concerns, but I believe I started before that person submitted, so it would be hard to restart. Should I just come up with a whole other idea and dump this project?

**Review by JosiasAurel — CHANGES_REQUESTED** [review]
It's irrelevant whether you started your project before someone else or not. It matters when it gets submitted though because I have no way of verifying when any of you started your project. 

My suggestion is to try something different.

**Comment by pizzalover125** [comment]
Just updated it to add lights!

**Review by JosiasAurel — CHANGES_REQUESTED** [review]
also why does this submission include `slang-translator`? Please remove this

**Comment by JosiasAurel** [comment]
I also get this error when running it in Chrome. 
image

**Comment by pizzalover125** [comment]
Uh... I just used the existing clone I made earlier. Is this a real problem?

**Comment by pizzalover125** [comment]
Just fixed!

**Comment by JosiasAurel** [comment]
I think the blinking lights could look a bit more like garlands. Checkout [festivitas](https://simonbs.gumroad.com/l/festivitas) for inspiration. 

It would be even nicer if it could be all around the browser window.

**Comment by pizzalover125** [comment]
Added a bunch of stuff! Now, the lights are in a set order and change positions based on the window size. The lights are also in this gumdrop shape, keeping the "minimalist" feel while resembling actual Christmas lights.

**Review by JosiasAurel — APPROVED** [review]
Cool. Please fill [this form](https://airtable.com/appgtKZwZBoOeFU7O/pagyeS51zr2kC1rp0/form) to get your grant

**Pull request merged**
