### PR TITLE
My Extension Submission 

### PR DESCRIPTION
**Pull request by SpecialistWealth**
# BrowserBuddy Extension Submission

## Project Details

1. **What is the name of your project?**  
   SakuraFlow

2. **How many hours did you spend developing this?**  
   - 3 Hours (learned how to make extensions)  
   - 5 hours to make the extension

3. **What problem does your extension solve, or what makes it unique?**  
   SakuraFlow helps users stay organized by providing a simple and calming interface to manage browser tabs. It allows users to search and easily close tabs, improving browser efficiency. Its unique sakura-inspired theme adds a peaceful, Japanese aesthetic to the tab management process.

4. **How many people have tested your extension?**  
   _(We recommend at least 3)_  
   14 people have tested the extension.

5. **Does your extension work in both Chrome and Firefox?**  
   Yes, the extension is compatible with both Chrome and Firefox.

---

## Additional Comments

The SakuraFlow extension is designed with a minimalist, Japanese-inspired interface, combining functionality with a soothing user experience. It's perfect for anyone looking to improve their browsing experience with an aesthetically pleasing design.

### CODE REVIEW

**Comment by SpecialistWealth** [comment]
Why This extension is useful...
So the problem I answered is that I tend to open too many tabs in the browser (see the picture below ) and sometime too much tabs opened and thus the browser doesn't show the little cross marks to close the tabs and sometimes opening those tabs causes the laptop to be stuck due to some ram issues :

Screenshot 2024-11-30 094512

thus I created an extension that lists all the tabs opened in all the browser windows and allows the user to close them with ease rather than messing up their workflow. 
The minimal UI I created was to not make things complicated 

Screenshot 2024-11-30 094621

even though the extension is pretty much simple, using it has made my life easier and I think my friends whom I sent this extension to try also said the same. 
I hope this does make other peoples life easier and especially to the people that have low ram capacity and stubborn laptops that freeze due to pretty much useless reasons 
The aim was to make browsing and managing tabs easier 
Thinking about personal growth, I learnt how to make a browser extension from scratch (the popup HTML JS , background JS , manifest JSON etc ) I was pretty much new to making extensions, a complete beginner but knew JS JSON HTML CSS I think I did make use of my time pretty wisely to learn a new domain making use of the current knowledge 
Thank you to my friends and HackClub !

**Review by JosiasAurel — COMMENTED** [review]
I like the idea of what you're doing with this. However one of the requirements is that your extension does something that another extension doesn't do yet. Currently there's an extension `TabRegex` that allows you to search for extension, select and close them. So how's yours different from that in terms of functinality?

**Comment by SpecialistWealth** [comment]
Hi 
I will add a feature that allows the user to click on the tab name and direct the browser to open this 
Actually I couldn't implement all the things I had in my mind because the browserbuddy program had a time constraint of November 30th (I discovered this on 29th) and I just finished up the initial sketch and uplaoded today morning 
If I have my own Repository which I will implement them (I think if I'm not right I cannot change the files right ..)

**Comment by SpecialistWealth** [comment]
Hi 
I have made some new implementation that makes this extension different from Tabregex 
Differences are that users can now visit the tabs from the tab manager 
I user is using youtube or any other tabs that have audio playing can easily mute them (which is not seen in the extension)
Users can search any tab using simple commands 
so hopefully this provides more fucntionality  for the user and more control

**Comment by JosiasAurel** [comment]
https://github.com/user-attachments/assets/f3fcba98-4664-4b22-bc24-640fb4635fec

It'll help to make the Mute/Unmute and pin/unpin buttons a bit more reactive

**Review by JosiasAurel — APPROVED** [review]
If you haven't already, please fill [this form](https://airtable.com/appgtKZwZBoOeFU7O/pagyeS51zr2kC1rp0/form) to get your grant.

**Pull request merged**
